# Generated by Django 4.2.30 on 2026-04-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_postattachment_commentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
