# Generated by Django 4.2.30 on 2026-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Member'), ('hr', 'HR'), ('ceo', 'CEO')], default='employee', max_length=20),
        ),
    ]
