# Generated by Django 4.2.30 on 2026-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationemail',
            name='role',
            field=models.CharField(blank=True, choices=[('employee', 'Member'), ('hr', 'HR'), ('ceo', 'CEO'), ('admin', 'Admin')], help_text='If set, only notified for posts targeted at this role. Leave blank for public post notifications.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='target_role',
            field=models.CharField(blank=True, choices=[('employee', 'Member'), ('hr', 'HR'), ('ceo', 'CEO'), ('admin', 'Admin')], help_text='If set, only the author and users with this role can see this post.', max_length=20, null=True),
        ),
    ]
