# Generated by Django 4.2.30 on 2026-09-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_add_slack_queue_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationemail',
            name='role',
            field=models.CharField(blank=True, choices=[('employee', 'Member'), ('hr', 'HR'), ('accountant', 'Accountant'), ('ceo', 'CEO'), ('admin', 'Admin')], help_text='If set, only notified for posts targeted at this role. Leave blank for public post notifications.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='target_role',
            field=models.CharField(blank=True, choices=[('employee', 'Member'), ('hr', 'HR'), ('accountant', 'Accountant'), ('ceo', 'CEO'), ('admin', 'Admin')], help_text='If set, only the author and users with this role can see this post.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Member'), ('hr', 'HR'), ('accountant', 'Accountant'), ('ceo', 'CEO'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
