# Generated by Django 4.2.30 on 2026-10-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_alter_notificationemail_role_alter_post_target_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_flag_individual',
            field=models.BooleanField(default=False, help_text='AI flagged this post as naming a specific individual.'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_flag_toxic',
            field=models.BooleanField(default=False, help_text='AI flagged this post as abusive or containing profanity.'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_label',
            field=models.CharField(blank=True, choices=[('constructive', 'Constructive'), ('critical_question', 'Critical Question'), ('serious_concern', 'Serious Concern'), ('personal_attack', 'Personal Attack'), ('logistics', 'Logistics')], default='', help_text='AI-assigned label for the nature of this post.', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_label_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
